### ISSUE TITLE
如果换一个小程序该如何操作

### ISSUE THREAD

**Issue by zkydsg** [yige233/yamada_helper#1]
就是微信能换一个小程序抢购吗

**Comment by yige233** [comment]
如果你说的是换成别家的网购小程序，应该是不行的，得重新抓包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月6日(周三) 上午10:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yige233/yamada_helper] 如果换一个小程序该如何操作 (Issue #1)




 
就是微信能换一个小程序抢购吗

**Comment by zkydsg** [comment]
好的谢谢啦
